- name: Initialize DB on master
  command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql-{{ postgres_version }}-setup initdb"
  args:
    creates: "{{ pg_data_dir }}/PG_VERSION"

- name: Template postgresql.conf for master
  template:
    src: postgresql.conf.j2
    dest: "{{ pg_data_dir }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: 0600

- name: Template pg_hba.conf for replication
  template:
    src: pg_hba.conf.j2
    dest: "{{ pg_data_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600

- name: Start PostgreSQL master
  service:
    name: postgresql-{{ postgres_version }}
    state: started
    enabled: true

- name: Create replication user
  become_user: postgres
  postgresql_user:
    name: "{{ replication_user }}"
    password: "{{ replication_password }}"
    role_attr_flags: "REPLICATION"