all:
  children:
    postgres:
      hosts:
        pgmaster:
        pgslave:
  vars:
    ansible_user: your_user
    postgres_version: 15
    pg_data_dir: /var/lib/pgsql/{{ postgres_version }}/data
    replication_user: replicator
    replication_password: replicator_pass
