all:
  children:
    postgres:
      hosts:
        pgmaster:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: root
          ansible_password: root
        pgslave:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: root
          ansible_password: root
  vars:
    postgres_version: 15
    pg_data_dir: /var/lib/pgsql/{{ postgres_version }}/data
    replication_user: replicator
    replication_password: replicator_pass
